server:
    port: 3000
  
db:
    type: 'postgres'
    port: 5432
    database: 'your-postgres-db-name'

jwt:
    expiresIn: 3600

redis:
    host: 'localhost'
    port: 6379
    ttl: 20
    max: 100

awsS3:
    endPoint: 'http://127.0.0.1:9000'
    awsS3AccessKeyId: 'your-access-key-username'
    awsS3SecretAccessKey: 'your-secret-access-key-username'
    s3BucketName: boilerplate-bucket

#this file is for unit test purpose (for test env)